package com.nitanmal.app.core.localization

enum class Language {
    SPANISH,
    ENGLISH
}

/**
 * Strings de la app. Solo se incluyen los que usa el flujo actual
 * (login + navbar + inicio + ideas + buzón + ajustes).
 */
data class AppStrings(
    // Navigation bar
    val navHome: String,
    val navIdeas: String,
    val navBuzon: String,
    val navProduccion: String,
    val navReuniones: String,
    val navPlanificador: String,
    val navAgenda: String,
    val navMetricas: String,
    val navSettings: String,

    // Login
    val appName: String,
    val loginTitle: String,
    val loginName: String,
    val loginEmail: String,
    val loginButton: String,
    val loginGoogleButton: String,

    // Home
    val homeIdeasActivas: String,
    val homePreguntasPendientes: String,
    val homeEpisodiosEnCurso: String,
    val homeReunionesProximas: String,
    val homeUltimasIdeas: String,
    val homeUltimasPreguntas: String,
    val homeEnProduccion: String,
    val homeProximaReunion: String,
    val homeVerTodas: String,
    val homeSinIdeas: String,
    val homeSinPreguntas: String,
    val homeSinEpisodios: String,
    val homeSinReuniones: String,

    // Ideas
    val ideasTitle: String,
    val ideasNueva: String,
    val ideasTituloLabel: String,
    val ideasContenidoLabel: String,
    val ideasEtiquetas: String,
    val ideasPublicar: String,
    val ideasVacio: String,
    val ideasComentarios: String,
    val ideasComentar: String,
    val ideasBorrar: String,
    val ideasFijar: String,
    val ideasEnlaces: String,
    val ideasAudios: String,
    val ideasGrabar: String,
    val ideasGrabando: String,
    val ideasAudioListo: String,
    val ideasMicPermiso: String,
    val ideasEditar: String,
    val ideasGuardar: String,
    val ideasEnlacesHint: String,
    val ideasTranscripcion: String,
    val ideasTranscribiendo: String,
    val ideasTranscribir: String,
    val ideasTranscripcionError: String,

    // Planificador
    val planTitle: String,
    val planGenerar: String,
    val planGenerarDesc: String,
    val planTema: String,
    val planTono: String,
    val planCta: String,
    val planPlataformas: String,
    val planGenerando: String,
    val planCrear: String,
    val planCopyLabel: String,
    val planFechaLabel: String,
    val planVacio: String,
    val planTodos: String,
    val planBorrar: String,

    // Canales / métricas
    val canalesTitle: String,
    val canalesEnVivo: String,
    val metricasTitle: String,
    val metricasVacio: String,
    val metricasSeguidores: String,
    val ideasConvertir: String,
    val ideasConvertirConfirm: String,

    // Notificaciones
    val notifTitle: String,
    val notifVacio: String,

    // Producción
    val prodTitle: String,
    val prodNuevo: String,
    val prodTituloLabel: String,
    val prodIdeaLabel: String,
    val prodCrear: String,
    val prodVacio: String,
    val prodEtapas: String,
    val prodGuardar: String,
    val prodResponsable: String,
    val prodFecha: String,
    val prodSubtareas: String,
    val prodAgregarSubtarea: String,
    val prodArchivoWeb: String,
    val prodBorrar: String,

    // Reuniones
    val reuTitle: String,
    val reuNueva: String,
    val reuProximas: String,
    val reuPasadas: String,
    val reuVacio: String,
    val reuTituloLabel: String,
    val reuFechaLabel: String,
    val reuHoraLabel: String,
    val reuLugarLabel: String,
    val reuDescripcionLabel: String,
    val reuCrear: String,

    // Buzón
    val buzonTitle: String,
    val buzonTodas: String,
    val buzonPendientes: String,
    val buzonRespondidas: String,
    val buzonVacio: String,
    val buzonMarcarRespondida: String,
    val buzonMarcarPendiente: String,

    // Fan
    val fanNavInicio: String,
    val fanNavEnVivo: String,
    val fanNavEpisodios: String,
    val fanNavMiZona: String,
    val fanNavCuenta: String,
    val fanEnVivoAhora: String,
    val fanVerEnYouTube: String,
    val fanProximoShow: String,
    val fanSinShows: String,
    val fanHorarios: String,
    val fanEpisodiosRecientes: String,
    val fanVerTodos: String,
    val fanBuzonCta: String,
    val fanBuzonDesc: String,
    val fanBuzonPlaceholder: String,
    val fanEnviar: String,
    val fanEntrar: String,
    val fanSorteoActivo: String,
    val fanPremiumLock: String,
    val fanShowNotes: String,
    val fanEscuchar: String,

    // Mi Zona
    val zonaTitle: String,
    val zonaSorteos: String,
    val zonaParticipar: String,
    val zonaParticipando: String,
    val zonaChances: String,
    val zonaParticipantes: String,
    val zonaEncuestas: String,
    val zonaVotos: String,
    val zonaSugerencias: String,
    val zonaSugerir: String,
    val zonaSugerirTema: String,
    val zonaSugerirInvitado: String,
    val zonaReferidos: String,
    val zonaReferidosDesc: String,
    val zonaDescargas: String,
    val zonaDescargar: String,
    val zonaVacio: String,

    // Cuenta
    val cuentaTitle: String,
    val cuentaPerfil: String,
    val cuentaApodo: String,
    val cuentaPais: String,
    val cuentaRegion: String,
    val cuentaTelefono: String,
    val cuentaGuardar: String,
    val cuentaPlan: String,
    val cuentaModoEquipo: String,
    val cuentaModoFan: String,

    // Navbar por rol / trabajo / admin / tema
    val navTrabajo: String,
    val navAdmin: String,
    val trabajoTitle: String,
    val trabajoVacio: String,
    val trabajoAtrasada: String,
    val trabajoEtapa: String,
    val trabajoIdea: String,
    val trabajoPost: String,
    val adminTitle: String,
    val adminEnVivo: String,
    val adminTransmitiendo: String,
    val adminVideoId: String,
    val adminTituloLive: String,
    val adminGuardar: String,
    val adminSorteos: String,
    val adminElegirGanador: String,
    val adminGanador: String,
    val adminCerrar: String,
    val adminAbrir: String,
    val temaTitulo: String,
    val temaWeb: String,
    val temaNeon: String,

    // Común
    val reintentar: String,
    val cargando: String,

    // Settings
    val settingsDarkTheme: String,
    val settingsSwitchSession: String,
    val settingsSignOut: String
)

private val SpanishStrings = AppStrings(
    navHome = "Inicio",
    navIdeas = "Ideas",
    navBuzon = "Buzón",
    navProduccion = "Producción",
    navReuniones = "Reuniones",
    navPlanificador = "Planner",
    navAgenda = "Agenda",
    navMetricas = "Métricas",
    navSettings = "Ajustes",

    appName = "Ni Tan Mal",
    loginTitle = "Iniciar Sesión",
    loginName = "Nombre",
    loginEmail = "Correo electrónico",
    loginButton = "Iniciar Sesión",
    loginGoogleButton = "Continuar con Google",

    homeIdeasActivas = "Ideas activas",
    homePreguntasPendientes = "Preguntas pendientes",
    homeEpisodiosEnCurso = "Episodios en curso",
    homeReunionesProximas = "Próximas reuniones",
    homeUltimasIdeas = "Últimas ideas",
    homeUltimasPreguntas = "Último del buzón",
    homeEnProduccion = "En producción",
    homeProximaReunion = "Próxima reunión",
    homeVerTodas = "Ver todas →",
    homeSinIdeas = "Aún no hay ideas. ¡Crea la primera!",
    homeSinPreguntas = "No hay preguntas del público todavía.",
    homeSinEpisodios = "No hay episodios en producción.",
    homeSinReuniones = "No hay reuniones agendadas.",

    ideasTitle = "Ideas",
    ideasNueva = "Nueva idea",
    ideasTituloLabel = "Título (opcional)",
    ideasContenidoLabel = "¿Cuál es la idea?",
    ideasEtiquetas = "Etiquetas",
    ideasPublicar = "Publicar",
    ideasVacio = "Aún no hay ideas. ¡Crea la primera!",
    ideasComentarios = "Comentarios",
    ideasComentar = "Escribe un comentario…",
    ideasBorrar = "Borrar idea",
    ideasFijar = "Fijar",
    ideasEnlaces = "Enlaces",
    ideasAudios = "Audios",
    ideasGrabar = "Grabar audio",
    ideasGrabando = "Grabando…",
    ideasAudioListo = "Audio grabado",
    ideasMicPermiso = "Permiso de micrófono denegado",
    ideasEditar = "Editar idea",
    ideasGuardar = "Guardar cambios",
    ideasEnlacesHint = "Enlaces (uno por línea)",
    ideasTranscripcion = "Transcripción",
    ideasTranscribiendo = "Transcribiendo…",
    ideasTranscribir = "Transcribir",
    ideasTranscripcionError = "La transcripción falló",

    planTitle = "Planificador",
    planGenerar = "Generar con IA",
    planGenerarDesc = "El agente creará borradores de posts para las plataformas que elijas.",
    planTema = "Tema",
    planTono = "Tono (opcional)",
    planCta = "Llamado a la acción (opcional)",
    planPlataformas = "Plataformas",
    planGenerando = "El agente está escribiendo…",
    planCrear = "Nuevo post",
    planCopyLabel = "Texto del post",
    planFechaLabel = "Fecha (AAAA-MM-DD, opcional)",
    planVacio = "No hay posts todavía. Genera borradores con IA o crea uno.",
    planTodos = "Todos",
    planBorrar = "Borrar post",

    canalesTitle = "Nuestros canales",
    canalesEnVivo = "EN VIVO",
    metricasTitle = "Métricas",
    metricasVacio = "Aún no hay métricas registradas.",
    metricasSeguidores = "seguidores",
    ideasConvertir = "Convertir a episodio",
    ideasConvertirConfirm = "Se creará un episodio en producción con esta idea y la idea quedará como Convertida.",

    notifTitle = "Notificaciones",
    notifVacio = "No tienes notificaciones.",

    prodTitle = "Producción",
    prodNuevo = "Nuevo episodio",
    prodTituloLabel = "Título del episodio",
    prodIdeaLabel = "Brief inicial (tema)",
    prodCrear = "Crear episodio",
    prodVacio = "Aún no hay episodios en producción.",
    prodEtapas = "Etapas",
    prodGuardar = "Guardar etapa",
    prodResponsable = "Responsable",
    prodFecha = "Fecha (AAAA-MM-DD)",
    prodSubtareas = "Subtareas",
    prodAgregarSubtarea = "Agregar subtarea…",
    prodArchivoWeb = "El archivo se sube desde el web",
    prodBorrar = "Borrar episodio",

    reuTitle = "Reuniones",
    reuNueva = "Nueva reunión",
    reuProximas = "Próximas",
    reuPasadas = "Pasadas",
    reuVacio = "No hay reuniones agendadas.",
    reuTituloLabel = "Título",
    reuFechaLabel = "Fecha (AAAA-MM-DD)",
    reuHoraLabel = "Hora (HH:MM)",
    reuLugarLabel = "Lugar (opcional)",
    reuDescripcionLabel = "Descripción (opcional)",
    reuCrear = "Agendar",

    buzonTitle = "Buzón",
    buzonTodas = "Todas",
    buzonPendientes = "Pendientes",
    buzonRespondidas = "Respondidas",
    buzonVacio = "No hay preguntas en este filtro.",
    buzonMarcarRespondida = "Marcar respondida",
    buzonMarcarPendiente = "Marcar pendiente",

    fanNavInicio = "Inicio",
    fanNavEnVivo = "En Vivo",
    fanNavEpisodios = "Episodios",
    fanNavMiZona = "Mi Zona",
    fanNavCuenta = "Cuenta",
    fanEnVivoAhora = "🔴 ESTAMOS EN VIVO",
    fanVerEnYouTube = "Ver en YouTube",
    fanProximoShow = "Próximo show",
    fanSinShows = "Pronto anunciaremos el próximo show.",
    fanHorarios = "Horarios",
    fanEpisodiosRecientes = "Episodios recientes",
    fanVerTodos = "Ver todos →",
    fanBuzonCta = "¿Tienes una pregunta o idea?",
    fanBuzonDesc = "Mándanos tu pregunta, tema o invitado. La leemos y puede terminar en un episodio.",
    fanBuzonPlaceholder = "Escribe tu pregunta, idea o invitado…",
    fanEnviar = "Enviar",
    fanEntrar = "Entrar",
    fanSorteoActivo = "Sorteo activo",
    fanPremiumLock = "Contenido premium 🔒",
    fanShowNotes = "Show notes",
    fanEscuchar = "Escuchar",

    zonaTitle = "Mi Zona",
    zonaSorteos = "Sorteos",
    zonaParticipar = "Participar",
    zonaParticipando = "Participando ✓",
    zonaChances = "chances",
    zonaParticipantes = "participantes",
    zonaEncuestas = "Encuestas",
    zonaVotos = "votos",
    zonaSugerencias = "Temas e invitados sugeridos",
    zonaSugerir = "Sugerir",
    zonaSugerirTema = "Tema",
    zonaSugerirInvitado = "Invitado",
    zonaReferidos = "Referidos",
    zonaReferidosDesc = "Invita amigos con tu enlace: más referidos, más chances en los sorteos.",
    zonaDescargas = "Descargas",
    zonaDescargar = "Descargar",
    zonaVacio = "Nada por aquí todavía.",

    cuentaTitle = "Cuenta",
    cuentaPerfil = "Perfil",
    cuentaApodo = "Apodo",
    cuentaPais = "País",
    cuentaRegion = "Región",
    cuentaTelefono = "Teléfono",
    cuentaGuardar = "Guardar perfil",
    cuentaPlan = "Plan",
    cuentaModoEquipo = "⇄ Modo equipo",
    cuentaModoFan = "⇄ Modo fan",

    navTrabajo = "Trabajo",
    navAdmin = "Admin",
    trabajoTitle = "Mi trabajo",
    trabajoVacio = "No tienes nada asignado. 🎉",
    trabajoAtrasada = "ATRASADA",
    trabajoEtapa = "Etapa",
    trabajoIdea = "Idea",
    trabajoPost = "Post",
    adminTitle = "Panel admin",
    adminEnVivo = "En vivo",
    adminTransmitiendo = "Transmitiendo ahora",
    adminVideoId = "Video ID o URL de YouTube",
    adminTituloLive = "Título de la transmisión",
    adminGuardar = "Guardar",
    adminSorteos = "Sorteos",
    adminElegirGanador = "Elegir ganador 🎲",
    adminGanador = "Ganador",
    adminCerrar = "Cerrar",
    adminAbrir = "Abrir",
    temaTitulo = "Tema de color",
    temaWeb = "Nocturno",
    temaNeon = "Neón",

    reintentar = "Reintentar",
    cargando = "Cargando…",

    settingsDarkTheme = "Tema oscuro",
    settingsSwitchSession = "Cambiar de portal",
    settingsSignOut = "Cerrar sesión"
)

private val EnglishStrings = AppStrings(
    navHome = "Home",
    navIdeas = "Ideas",
    navBuzon = "Inbox",
    navProduccion = "Production",
    navReuniones = "Meetings",
    navPlanificador = "Planner",
    navAgenda = "Agenda",
    navMetricas = "Metrics",
    navSettings = "Settings",

    appName = "Ni Tan Mal",
    loginTitle = "Sign In",
    loginName = "Name",
    loginEmail = "Email",
    loginButton = "Sign In",
    loginGoogleButton = "Continue with Google",

    homeIdeasActivas = "Active ideas",
    homePreguntasPendientes = "Pending questions",
    homeEpisodiosEnCurso = "Episodes in progress",
    homeReunionesProximas = "Upcoming meetings",
    homeUltimasIdeas = "Latest ideas",
    homeUltimasPreguntas = "Latest from inbox",
    homeEnProduccion = "In production",
    homeProximaReunion = "Next meeting",
    homeVerTodas = "See all →",
    homeSinIdeas = "No ideas yet. Create the first one!",
    homeSinPreguntas = "No audience questions yet.",
    homeSinEpisodios = "No episodes in production.",
    homeSinReuniones = "No meetings scheduled.",

    ideasTitle = "Ideas",
    ideasNueva = "New idea",
    ideasTituloLabel = "Title (optional)",
    ideasContenidoLabel = "What's the idea?",
    ideasEtiquetas = "Tags",
    ideasPublicar = "Publish",
    ideasVacio = "No ideas yet. Create the first one!",
    ideasComentarios = "Comments",
    ideasComentar = "Write a comment…",
    ideasBorrar = "Delete idea",
    ideasFijar = "Pin",
    ideasEnlaces = "Links",
    ideasAudios = "Audios",
    ideasGrabar = "Record audio",
    ideasGrabando = "Recording…",
    ideasAudioListo = "Audio recorded",
    ideasMicPermiso = "Microphone permission denied",
    ideasEditar = "Edit idea",
    ideasGuardar = "Save changes",
    ideasEnlacesHint = "Links (one per line)",
    ideasTranscripcion = "Transcript",
    ideasTranscribiendo = "Transcribing…",
    ideasTranscribir = "Transcribe",
    ideasTranscripcionError = "Transcription failed",

    planTitle = "Planner",
    planGenerar = "Generate with AI",
    planGenerarDesc = "The agent will draft posts for the platforms you pick.",
    planTema = "Topic",
    planTono = "Tone (optional)",
    planCta = "Call to action (optional)",
    planPlataformas = "Platforms",
    planGenerando = "The agent is writing…",
    planCrear = "New post",
    planCopyLabel = "Post copy",
    planFechaLabel = "Date (YYYY-MM-DD, optional)",
    planVacio = "No posts yet. Generate drafts with AI or create one.",
    planTodos = "All",
    planBorrar = "Delete post",

    canalesTitle = "Our channels",
    canalesEnVivo = "LIVE",
    metricasTitle = "Metrics",
    metricasVacio = "No metrics recorded yet.",
    metricasSeguidores = "followers",
    ideasConvertir = "Convert to episode",
    ideasConvertirConfirm = "A production episode will be created from this idea and the idea will be marked as Converted.",

    notifTitle = "Notifications",
    notifVacio = "You have no notifications.",

    prodTitle = "Production",
    prodNuevo = "New episode",
    prodTituloLabel = "Episode title",
    prodIdeaLabel = "Initial brief (topic)",
    prodCrear = "Create episode",
    prodVacio = "No episodes in production yet.",
    prodEtapas = "Stages",
    prodGuardar = "Save stage",
    prodResponsable = "Owner",
    prodFecha = "Date (YYYY-MM-DD)",
    prodSubtareas = "Subtasks",
    prodAgregarSubtarea = "Add subtask…",
    prodArchivoWeb = "Files are uploaded from the web app",
    prodBorrar = "Delete episode",

    reuTitle = "Meetings",
    reuNueva = "New meeting",
    reuProximas = "Upcoming",
    reuPasadas = "Past",
    reuVacio = "No meetings scheduled.",
    reuTituloLabel = "Title",
    reuFechaLabel = "Date (YYYY-MM-DD)",
    reuHoraLabel = "Time (HH:MM)",
    reuLugarLabel = "Place (optional)",
    reuDescripcionLabel = "Description (optional)",
    reuCrear = "Schedule",

    buzonTitle = "Inbox",
    buzonTodas = "All",
    buzonPendientes = "Pending",
    buzonRespondidas = "Answered",
    buzonVacio = "No questions in this filter.",
    buzonMarcarRespondida = "Mark answered",
    buzonMarcarPendiente = "Mark pending",

    fanNavInicio = "Home",
    fanNavEnVivo = "Live",
    fanNavEpisodios = "Episodes",
    fanNavMiZona = "My Zone",
    fanNavCuenta = "Account",
    fanEnVivoAhora = "🔴 WE'RE LIVE",
    fanVerEnYouTube = "Watch on YouTube",
    fanProximoShow = "Next show",
    fanSinShows = "We'll announce the next show soon.",
    fanHorarios = "Schedule",
    fanEpisodiosRecientes = "Recent episodes",
    fanVerTodos = "See all →",
    fanBuzonCta = "Got a question or idea?",
    fanBuzonDesc = "Send us your question, topic or guest. We read them and they may end up in an episode.",
    fanBuzonPlaceholder = "Write your question, idea or guest…",
    fanEnviar = "Send",
    fanEntrar = "Sign in",
    fanSorteoActivo = "Active giveaway",
    fanPremiumLock = "Premium content 🔒",
    fanShowNotes = "Show notes",
    fanEscuchar = "Listen",

    zonaTitle = "My Zone",
    zonaSorteos = "Giveaways",
    zonaParticipar = "Enter",
    zonaParticipando = "Entered ✓",
    zonaChances = "entries",
    zonaParticipantes = "participants",
    zonaEncuestas = "Polls",
    zonaVotos = "votes",
    zonaSugerencias = "Suggested topics & guests",
    zonaSugerir = "Suggest",
    zonaSugerirTema = "Topic",
    zonaSugerirInvitado = "Guest",
    zonaReferidos = "Referrals",
    zonaReferidosDesc = "Invite friends with your link: more referrals, more giveaway entries.",
    zonaDescargas = "Downloads",
    zonaDescargar = "Download",
    zonaVacio = "Nothing here yet.",

    cuentaTitle = "Account",
    cuentaPerfil = "Profile",
    cuentaApodo = "Nickname",
    cuentaPais = "Country",
    cuentaRegion = "Region",
    cuentaTelefono = "Phone",
    cuentaGuardar = "Save profile",
    cuentaPlan = "Plan",
    cuentaModoEquipo = "⇄ Team mode",
    cuentaModoFan = "⇄ Fan mode",

    navTrabajo = "Work",
    navAdmin = "Admin",
    trabajoTitle = "My work",
    trabajoVacio = "Nothing assigned to you. 🎉",
    trabajoAtrasada = "OVERDUE",
    trabajoEtapa = "Stage",
    trabajoIdea = "Idea",
    trabajoPost = "Post",
    adminTitle = "Admin panel",
    adminEnVivo = "Live",
    adminTransmitiendo = "Live right now",
    adminVideoId = "YouTube video ID or URL",
    adminTituloLive = "Stream title",
    adminGuardar = "Save",
    adminSorteos = "Giveaways",
    adminElegirGanador = "Pick winner 🎲",
    adminGanador = "Winner",
    adminCerrar = "Close",
    adminAbrir = "Open",
    temaTitulo = "Color theme",
    temaWeb = "Night",
    temaNeon = "Neon",

    reintentar = "Retry",
    cargando = "Loading…",

    settingsDarkTheme = "Dark theme",
    settingsSwitchSession = "Switch workspace",
    settingsSignOut = "Sign out"
)

fun getStrings(language: Language): AppStrings = when (language) {
    Language.SPANISH -> SpanishStrings
    Language.ENGLISH -> EnglishStrings
}
